### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by arduR-O** [N0vice17/graph-visualizer#1]
Hey I found your project via the resume you uploaded on linkedin. It's an impressive project but I feel if you could make the following changes it would greatly improve the UX

1) In the input fields, especially for edges, add placeholder text showing what is the format to add edges
2) In the graph specification button, add a downward arrow to indicate it's a menu, maybe make it expand on hover, since I had no idea it was a menu till I saw the source code
3) make the draw mode default, since the first instinct of user would be to try drawing graphs manually
4) Handle the edge of case of 1 node, the node that appears is really large

I hope you find these suggestions helpful!!

**Comment by N0vice17** [comment]
Thanks for pointing out these things. Actually i am building the version 2 of this graph visualizer it will be having a better UI and UX and will have more functionalities compared to this one. Again Thanks for pointing out these mistakes made by me
